const discos = [
    {
        id: '8392678',
        titulo: 'Foregrow EP',
        artista: 'John Frusciante',
        categoria: 'Simple',
        anio: '2016',
        img: '/assets/R-8392678-1460792762-1145.jpg',
        stock: 10,
        precio: 19.95,
        sello: 'Acid Test',
        genero: 'Electronica',
        descripcion: 'Foregrow es el séptimo EP lanzado por el músico estadounidense John Frusciante. Fue lanzado para el Record Store Day el 16 de abril de 2016 por Acid Test. - 12" - 33 RPM 45 RPM EP Record Store Day. The EP is a compilation put together by Acid Test records gathering four of Johns recordings during his initial songwriting period with his more experimental, electronic music which directly followed his work for the Trickfinger record. These tracks were also conceived around the same time of his recordings with Speed Dealer Moms, and even feature a modular synthesizer developed for John by his bandmate Chris McDonald. His free download album Renoise Tracks 2009-2011 available on his SoundCloud/Bandcamp pages was recorded during this time period as well.'
    },
    {
        id: '2820289',
        titulo: 'Buddy Holly',
        artista: 'Buddy Holly',
        categoria: 'Vinilo',
        anio: '1983',
        img: '/assets/R-2820289-1604757284-2458.jpg',
        stock: 5,
        precio: 10.42,
        sello: 'All Round Trading',
        genero: 'Rockabilly',
        descripcion: 'Charles Hardin Holley, más conocido como Buddy Holly (Lubbock, Texas; 7 de septiembre de 1936-Clear Lake, Iowa; 3 de febrero de 1959),4​2​ fue un compositor y cantante estadounidense de mediados de la década de 1950, considerado hoy en día como uno de los pioneros y creadores del Rock and Roll. Holly fue descrito por el crítico Bruce Eder como: «la fuerza creativa más influyente del rock and roll primigenio. Si bien durante su corta trayectoria solo alcanzó a publicar tres álbumes de estudio, su innovación y sobresaliente obra musical sirvieron de inspiración y fue la influencia de muchos músicos posteriores como The Beatles, The Hollies, The Beach Boys, The Rolling Stones, Don McLean, Bob Dylan, entre otros, además de ejercer una profunda influencia en la música popular.'
    },
    {
        id: '11557517',
        titulo: 'Elgin Avenue Breakdown Revisited',
        artista: 'The 101ers',
        categoria: 'Vinilo Doble',
        anio: '2015',
        img: '/assets/R-11557517-1518460017-3306.jpg',
        stock: 5,
        precio: 23.73,
        sello: 'Andalucia Records',
        genero: 'Rock',
        descripcion: 'Elgin Avenue Breakdown es un álbum recopilatorio de la banda de pub rock liderada por Joe Strummer, The 101ers, antes de que este se integrara a The Clash. Fue lanzado en 1981 debido a la popularidad de The Clash. En este disco se encuentra el único sencillo de la banda Keys to Your Heart'
    },
    {
        id: '5504349',
        titulo: 'Abbey Road',
        artista: 'The Beatles',
        categoria: 'Vinilo',
        anio: '1969',
        img: '/assets/R-5504349-1395081574-6216.jpg',
        stock: 3,
        precio: 25.48,
        sello: 'Apple Records',
        genero: 'Rock',
        descripcion: 'Abbey Road es el undécimo álbum de estudio (duodécimo en estados unidos) publicado por la banda británica de rock The Beatles, sería lanzado el 26 de septiembre de 1969 en Reino Unido por Apple Records. Las grabaciones de Abbey Road comenzarían en abril de 1969, haciendo de este el último álbum grabado por la banda, ya que Let It Be, lanzado en 1970, había sido grabado con anterioridad. El álbum se caracterizó por la presencia de un medley en el lado B, una larga pieza de 16 minutos, que constaba de ocho canciones enlazadas una tras otra sucesivamente. También fue producido y orquestado por George Martin, con Geoff Emerick como ingeniero de grabación. '
    },
    {
        id: '5425037',
        titulo: 'In The Mountain In The Cloud',
        artista: 'Portugal. The Man',
        categoria: 'Vinilo',
        anio: '2011',
        img: '/assets/R-5425037-1393030366-8043.jpg',
        stock: 100,
        precio: 17.01,
        sello: 'Atlantic',
        genero: 'Psychedelic Rock',
        descripcion: 'In the Mountain in the Cloud es el sexto Álbum de estudio de la banda de rock estadounidense Portugal. The Man. Fue grabado durante un perí­odo de ocho meses y producido por John Hill, el lí­der de la banda, John Gourley, y Casey Bates.'
    },
    {
        id: '2112572',
        titulo: 'Gene Vincent Greatest',
        artista: 'Gene Vincent',
        categoria: 'Vinilo',
        anio: '1959',
        img: '/assets/R-2112572-1556402471-9401.jpg',
        stock: 100,
        precio: 12.82,
        sello: 'Capitol Records',
        genero: 'Rockabilly',
        descripcion: 'Eugene Vincent Craddock, conocido artí­sticamente como Gene Vincent, fue un cantante estadounidense de música rockabilly, conocido principalmente por su éxito «Be-Bop-A-Lula» y su grupo The Blue Caps. Era apodado El Prí­ncipe Negro por su indumentaria de cuero negro, con la cual se presentaba en sus conciertos.'
    },
    {
        id: '2726086',
        titulo: 'Les And Mary',
        artista: 'Les Paul & Mary Ford',
        categoria: 'Vinilo 10"',
        anio: '1955',
        img: '/assets/R-2726086-1309924113.jpg',
        stock: 100,
        precio: 10.01,
        sello: 'Capitol Records',
        genero: 'Pop',
        descripcion: 'Les Paul y Mary Ford fueron un popular dúo musical de marido y mujer de la década de 1950 que actuaron y grabaron durante 1945-1963. Ambos cantaban y tocaban guitarras. '
    },
    {
        id: '8645720',
        titulo: 'Pet Sounds',
        artista: 'The Beach Boys',
        categoria: 'Vinilo',
        anio: '1969',
        img: '/assets/R-8645720-1505411453-7137.jpg',
        stock: 100,
        precio: 22.75,
        sello: 'Capitol Records',
        genero: 'Rock',
        descripcion: 'Pet Sounds es el undécimo álbum de estudio de la banda de rock estadounidense The Beach Boys, lanzado el 16 de mayo de 1966. A diferencia de sus anteriores trabajos, en donde tocaban rock and roll y surf, en este predomina el pop barroco, con un contenido lí­rico más sofisticado siendo más reflexivo y sentimental.'
    },
    
    {
        id: '784023',
        titulo: 'The Clash',
        artista: 'The Clash',
        categoria: 'Vinilo',
        anio: '1982',
        img: '/assets/R-784023-1231507049.jpg',
        stock: 100,
        precio: 15.52,
        sello: 'CBS Records',
        genero: 'Punk',
        descripcion: 'The Clash es el nombre del album debut lanzado por la banda punk britanica The Clash. Fue publicado en dos diferentes versiones, la original editada en 1977 en Gran Bretaña y Europa, y una distinta lanzada en el mercado estadounidense en 1979.'
    },
    {
        id: '1075934',
        titulo: 'Give Em Enough Rope',
        artista: 'The Clash',
        categoria: 'Vinilo',
        anio: '1979',
        img: '/assets/R-1075934-1569772817-8626.jpg',
        stock: 100,
        precio: 12.34,
        sello: 'CBS Records',
        genero: 'Punk',
        descripcion: 'The Clash es el nombre del album debut lanzado por la banda punk britanica The Clash. Fue publicado en dos diferentes versiones, la original editada en 1977 en Gran Bretaña y Europa, y una distinta lanzada en el mercado estadounidense en 1979.'
    },
    {
        id: '8528867',
        titulo: 'Defcon 5...4...3...2...1',
        artista: 'Man Or Astro-Man?',
        categoria: 'Vinilo',
        anio: '2016',
        img: '/assets/R-8528867-1477947721-4635.jpg',
        stock: 100,
        precio: 18.19,
        sello: 'Chunklet Magazine',
        genero: 'Surf',
        descripcion: 'Man or Astro-man? es una banda de surf rock formada en 1992 en Auburn, Alabama. Sus miembros argumentaban ser seres extraterrestres cuya nave se impactó contra la Tierra, así­ que decidieron formar una banda para poder infiltrarse entre los humanos'
    },
    {
        id: '8928025',
        titulo: 'London Calling: 30th Anniversary Edition',
        artista: 'The Clash',
        categoria: 'CD',
        anio: '2016',
        img: '/assets/R-8928025-1471647353-2967.jpg',
        stock: 100,
        precio: 18.50,
        sello: 'Columbia',
        genero: 'Rock',
        descripcion: 'London Calling es el tercer Album de estudio de la banda británica de punk The Clash, lanzado el 14 de diciembre de 1979, por CBS Records en el Reino Unido y en enero de 1980 por Epic Records en Estados Unidos.'
    },
    {
        id: '823440',
        titulo: 'Highway 61 Revisited',
        artista: 'Bob Dylan',
        categoria: 'Vinilo',
        anio: '2001',
        img: '/assets/R-823440-1282593405.jpg',
        stock: 100,
        precio: 18.50,
        sello: 'Columbia',
        genero: 'Rock',
        descripcion: 'Highway 61 Revisited es el sexto álbum de estudio del músico estadounidense Bob Dylan, publicado por la compañía discográfica Columbia Records en agosto de 1965. Después de comenzar su carrera tocando música folk y de grabar en acústico —a excepción de la primera cara de Bringing It All Back Home—, Dylan utilizó por primera vez una banda de acompañamiento en todas las canciones de Highway 61 Revisited, grabadas en Nueva York entre junio y agosto de 1965.'
    },
    {
        id: '7322988',
        titulo: 'Eddie Cochran',
        artista: 'Eddie Cochran',
        categoria: 'Vinilo',
        anio: '2015',
        img: '/assets/R-7322988-1438878507-1524.jpg',
        stock: 100,
        precio: 10.41,
        sello: 'DOL Records',
        genero: 'Rockabilly',
        descripcion: 'Edward Ray "Eddie" Cochran (Albert Lea, Minnesota; 3 de octubre de 1938-Somerset, Inglaterra; 17 de abril de 1960) fue un músico estadounidense de rock and roll, considerado como uno de los pioneros del género. Las canciones de Cochran, como "Twenty-Flight Rock", "Summertime Blues", "Cmon Everybody" y "Somethin Else", capturaron la frustración y el deseo de los adolescentes a mediados de los años cincuenta y principios de los sesenta contra los cánones establecidos. Experimentó con grabación de multipista, técnicas de distorsión y sobre-grabación incluso en sus primeros singles.'
    },
    {
        id: '8442455',
        titulo: 'Surfers Choice',
        artista: 'Dick Dale & His Del-Tones',
        categoria: 'Vinilo',
        anio: '1966',
        img: '/assets/R-8442455-1461691963-3343.jpg',
        stock: 100,
        precio: 10.41,
        sello: 'DOL Records',
        genero: 'Surf',
        descripcion: 'Dick Dale, cuyo nombre completo es Richard Anthony Monsour, fue un músico y guitarrista estadounidense. Fue pionero del surf rock junto a The Ventures, así­ como lí­der de la banda Dick Dale & The Del-Tones. '
    },
    {
        id: '8796391',
        titulo: 'Dance Album Of Carl Perkins',
        artista: 'Carl Perkins',
        categoria: 'Vinilo',
        anio: '2016',
        img: '/assets/R-8796391-1468947709-5661.jpg',
        stock: 100,
        precio: 10.41,
        sello: 'DOL Records',
        genero: 'Rockabilly',
        descripcion: 'Carl Lee Perkins (Ridgely, Tennessee; 9 de abril de 1932-Jackson, Tennessee; 19 de enero de 1998) fue un cantante estadounidense pionero del rockabilly, una mezcla de rhythm and blues y música country, que inició su carrera con Sun Records en Memphis al comienzo de los años 1950. Fue introducido en el Salón de la Fama del Rock and Roll y además ocupa el puesto 99 de los 100 Grandes Artistas de la revista Rolling Stone'
    },
    {
        id: '8206315',
        titulo: 'Built For Speed',
        artista: 'Stray Cats',
        categoria: 'Vinilo',
        anio: '1982',
        img: '/assets/R-8206315-1589311519-1248.jpg',
        stock: 100,
        precio: 13.16,
        sello: 'EMI',
        genero: 'Rockabilly',
        descripcion: 'Built for Speed es el primer Album estadounidense de la banda "rockabilly" Stray Cats. Fue el Album con el que consiguieron mayor exito. Es un recopilatario de doce canciones tomadas de sus dos primeros discos que fueron solo publicados en U.K'
    },
    {
        id: '13690579',
        titulo: 'Are You Experienced',
        artista: 'The Jimi Hendrix Experience',
        categoria: 'Vinilo',
        anio: '2010',
        img: '/assets/R-2416800-1633595158-4336.jpg',
        stock: 100,
        precio: 31.85,
        sello: 'Experience Hendrix',
        genero: 'Rock',
        descripcion: 'Are You Experienced es el Álbum debut de la banda angloamericana de rock Jimi Hendrix Experience, publicado en 1967 a través del sello discográfico Track Records. El LP fue un éxito comercial y de crí­tica y uno de los más exitosos discos debut de la historia del rock.'
    },
    {
        id: '2416800',
        titulo: 'Thriller',
        artista: 'Michael Jackson',
        categoria: 'Vinilo',
        anio: '1982',
        img: '/assets/R-13690579-1612741736-5382.jpg',
        stock: 100,
        precio: 18.20,
        sello: 'Epica',
        genero: 'Funk / Soul',
        descripcion: 'Thriller es el sexto álbum de estudio del cantante estadounidense Michael Jackson. Fue lanzado el 30 de noviembre de 1982 por Epic Records. '
    },
    {
        id: '3362394',
        titulo: 'Electric Ladyland',
        artista: 'The Jimi Hendrix Experience',
        categoria: 'CD',
        anio: '2010',
        img: '/assets/R-3362394-1327382749.jpg',
        stock: 100,
        precio: 26.31,
        sello: 'Experience Hendrix',
        genero: 'Rock',
        descripcion: 'Electric Ladyland es el tercer álbum de The Jimi Hendrix Experience, el cual fue lanzado en 1968, siendo el último de la banda. Es un álbum doble considerado uno de sus trabajos más destacables. Muestra elementos que anticipan el rock progresivo (Aunque no pertenece a este género pero puede ser considerado una influencia) en canciones como "1983... (A Merman I Should Turn to Be)", y la versión de la canción de Bob Dylan "All Along The Watchtower" (que suele ser considerada por muchos como la mejor versión de la misma, incluso por Dylan).'
    },
    {
        id: '7036268',
        titulo: 'Hypnophobia',
        artista: 'Jacco Gardner',
        categoria: 'CD',
        anio: '2015',
        img: '/assets/R-7036268-1432369935-4838.jpg',
        stock: 100,
        precio: 12.38,
        sello: 'Full Time Hobby',
        genero: 'Psychedelic Rock',
        descripcion: 'Jacco Gardner es un músico holandés nacido el 9 de abril del año 1988 en Hoogeveen, localidad de la provincia de Drente. Amante del pop psicodélico y barroco de los años 60, lo primero que publicó Jacco en disco fue “Year One” (2010), un trabajo editado en Grey Past Records y acreditado a The Skywalers, dúo que formó junto a Hugo Van de Poel en el que tanto se muestra su deuda con la lisergia como con el rock garajero 60s.'
    },
    
    {
        id: '7103501',
        titulo: 'Surf Explos\u00e3o',
        artista: 'The Dead Rocks',
        categoria: 'Vinilo',
        anio: '2015',
        img: '/assets/R-7103501-1433798555-2624.jpg',
        stock: 100,
        precio: 15.38,
        sello: 'Groovie Records',
        genero: 'Surf',
        descripcion: 'It has been more than 13 years since the Brazilian band THE DEAD ROCKS began its brilliant musical career. Since then, unforgettable shows have been presented in parties, venues, wedding parties, graduation parties, pubs, bars, balls, big musical and artist festivals.'
    },
    {
        id: '4398091',
        titulo: 'Great Balls Of Fire (20 Original Hit Recordings)',
        artista: 'Jerry Lee Lewis',
        categoria: 'CD',
        anio: '1989',
        img: '/assets/R-4398091-1392089488-2439.jpg',
        stock: 100,
        precio: 5.57,
        sello: 'Hallmark Records',
        genero: 'Rockabilly',
        descripcion: 'Jerry Lee Lewis (Ferriday, Luisiana, 29 de septiembre de 1935-Condado de DeSoto, Misisipi, 28 de octubre de 2022)​ fue un cantante, compositor y pianista estadounidense, pionero del rock and roll. Fue ampliamente considerado como uno de los cantantes más influyentes e importantes del rock y uno de los pianistas más influyentes del siglo xx. Apodado "The Killer" por su fuerte personalidad y su puesta en escena, y tras ser considerado una seria alternativa frente a Elvis Presley, el "Rey del Rock". Su popularidad decayó a finales de los años cincuenta al hacerse público que se casó con su prima Myra Gale Brown, de 13 años de edad. Su carrera resurgió a mediados de los años 60 con varios éxitos en la música country.'
    },
    {
        id: '6800500',
        titulo: 'Los Charapas De Oro',
        artista: 'Los Mirlos',
        categoria: 'Vinilo',
        anio: '1975',
        img: '/assets/R-6800500-1632680844-8929.jpg',
        stock: 100,
        precio: 40.57,
        sello: 'Infopesa',
        genero: 'Cumbia Peruana',
        descripcion: 'Los Mirlos son los creadores de la cumbia amazónica, una de las muchas manifestaciones de la cumbia peruana. Es un grupo de larga trayectoria, originario de la ciudad de Moyobamba,​ en el departamento de San Martín, cuyo origen selvático les valió el apodo de "Los Charapas de Oro". Sus inicios se remontan al año 1968 cuando se llamaban Los Saetas'
    },
    {
        id: '1981738',
        titulo: 'The Psychedelic Sounds Of The 13th Floor Elevators',
        artista: '13th Floor Elevators',
        categoria: 'Vinilo',
        anio: '1967',
        img: '/assets/R-1981738-1577774098-1147.jpg',
        stock: 100,
        precio: 330.47,
        sello: 'International Artists',
        genero: 'Psychedelic Rock',
        descripcion: 'The Psychedelic Sounds of the 13th Floor Elevators es el primer album de la banda estadounidense 13th Floor Elevators. El sonido del album mezcla elementos del folk, garage rock, blues y psicodelia.'
    },
    {
        id: '2070299',
        titulo: 'Cold Fact',
        artista: 'Sixto Rodriguez',
        categoria: 'Vinilo',
        anio: '2010',
        img: '/assets/R-2070299-1441723214-1339.jpg',
        stock: 100,
        precio: 30.47,
        sello: 'Light In The Attic',
        genero: 'Folk Rock',
        descripcion: 'Cold Fact fue el primer álbum del músico y compositor estadounidense Rodrí­guez, editado en marzo de 1970 por el sello Sussex Records. Incluye canciones que combinan folk rock, rock psicodélico y pop con letras de contenido social'
    },
    {
        id: '2771111',
        titulo: 'The Explosive Freddy Cannon',
        artista: 'Freddy Cannon',
        categoria: 'Vinilo',
        anio: '1980',
        img: '/assets/R-2771111-1422739149-7583.jpg',
        stock: 100,
        precio: 3.64,
        sello: 'Lollipop Records',
        genero: 'Rock',
        descripcion: 'Frederick Anthony Picariello, Jr., más conocido por su nombre artístico Freddy Cannon, es un cantante de rock and roll estadounidense, cuyos mayores éxitos internacionales son "Tallahassee Lassie", "Way Down Yonder in New Orleans" y "Palisades Park"'
    },
    {
        id: '5108220',
        titulo: 'Room On Fire',
        artista: 'The Strokes',
        categoria: 'CD',
        anio: '2013',
        img: '/assets/R-5108220-1394568749-5990.jpg',
        stock: 100,
        precio: 24.14,
        sello: 'RCA',
        genero: 'Rock',
        descripcion: 'Room On Fire es el segundo álbum de la banda The Strokes. Publicado en octubre de 2003, incluyendo tres sencillos: «12:51», «Reptilia» y «The End Has No End». El productor ganador del Grammy, Nigel Godrich (Radiohead, Travis, Beck), fue inicialmente establecido como productor de Room On Fire, pero The Strokes sintieron que él hizo sus canciones «carentes de alma», así que volvieron con su productor de Is This It, Gordon Raphael. Room on Fire vendió más de 50.000 copias en su primera semana en Estados Unidos quedando en número 4 en la lista Billboard, para 2005 el álbum vendió más de 500.000 copias en Estados Unidos y fue certificado Oro, en Reino Unido vendió más de 300.000 copias y fue certificado platino. El álbum hasta la fecha ha logrado vender más de 3 millones de copias en todo el mundo.'
    },
    {
        id: '4660729',
        titulo: 'The History Of Blue Beat',
        artista: 'Various',
        categoria: 'Vinilo',
        anio: '2013',
        img: '/assets/R-4660729-1371400690-6910.jpg',
        stock: 100,
        precio: 20.14,
        sello: 'Not Now Music',
        genero: 'Reggae',
        descripcion: 'Blue Beat Records es un sello discogrífico ingles que lanzo musica jamaicana de rhythm and blues y ska en la decada de 1960 y decadas posteriores.'
    },
    {
        id: '6478358',
        titulo: 'Shakers For You!',
        artista: 'Los Shakers',
        categoria: 'Vinilo',
        anio: '1966',
        img: '/assets/R-6478358-1420218443-9004.jpg',
        stock: 100,
        precio: 27.76,
        sello: 'Odeon',
        genero: 'Rock',
        descripcion: 'Originally released in 1966, Shakers For You was the second LP by Los Shakers, the legendary beat/pop band from Uruguay. An album clearly influenced by Help!, Rubber Soul and Revolver, but showing a band that were more than mere copycats, offering some revolutionary compositions and influences such as bossa-nova.'
    },
    {
        id: '12345678',
        titulo: 'El Disco del Helado',
        artista: 'Los Shakers',
        categoria: 'Cassette',
        anio: '2020',
        img: '/assets/cassette-del-helado600.jpg',
        stock: 100,
        precio: 12.76,
        sello: 'Shaemingow Records',
        genero: 'Surf',
        descripcion: 'Mezcla y Master: Santiago Fontona en Farmbox Studios en Nueva Zelanda. Grabado entre Setiembre y Diciembre del 2019 en Montevideo y Canelones: Baterías: en Estudio Módulo por Juan Branaá, Guitarras, Bajos y Poderes: Blast Off Records, en la Casa de Pablito y en Casa de Juanma. Los Ultraman: Alejandro Ferreira (guitarras, lapsteel y teclados), Pablo Martín (guitarras, teclados, coros y fx), Fabricio Gómez (bajo), Juan Manuel Cayota (batería, percusiones, bajos, guitarras y teclados)'
    },
    {
        id: '12345578',
        titulo: 'Reverb Sounds',
        artista: 'Pasajeros del Malaysia Airlines',
        categoria: 'Cassette',
        anio: '2020',
        img: '/assets/pma-cassette_1200.jpg',
        stock: 100,
        precio: 12.76,
        sello: 'Shaemingow Records',
        genero: 'Reggae',
        descripcion: 'Reverb sounds, fue grabado en junio del 2019 en una sesión eterna un sábado frío, en el estudio, Septimopiso, a cargo de la noble y atenta dirección de Mateo Flores.Contamos a su vez, en dicha sesión, con la asistencia erudita y amable de Pablo Balmelli. Los overdubs y las voces, así como la mezcla, se realizaron en estudio BlastOff, a cargo de Mateo Flores y los integrantes de la banda durante todo el resto del 2019 y algo del 2020.'
    },
    {
        id: '2917760',
        titulo: 'Socorro!',
        artista: 'The Beatles',
        categoria: 'Vinilo',
        anio: '1965',
        img: '/assets/R-2917760-1380175582-6261.jpg',
        stock: 100,
        precio: 27.76,
        sello: 'Odeon',
        genero: 'Rock',
        descripcion: 'A mediados de 1965 aparece este disco que se ciñe a la versión original británica y no a la edición USA de la banda sonora del film. Editado bajo els ello Odeon, será una de las últimas carátulas en las que se incluyan traducciones del título u otra modificación a la imagen original.'
    },
    {
        id: '4501773',
        titulo: 'Beatles For Sale',
        artista: 'The Beatles',
        categoria: 'Vinilo',
        anio: '1965',
        img: '/assets/R-4501773-1676905761-6902.jpg',
        stock: 100,
        precio: 35.25,
        sello: 'Odeon',
        genero: 'Rock',
        descripcion: 'A comienzos de 1965 se suma un nuevo álbum de The Beatles. Nuevamente bajo el sello Odeon, se adpata exactamente al set list del original británico. Esta será una característica que se seguirá de aquí en adelante, sin apelar a las versiones estadounidenses que sumaban o restaban temas, según fuera el sello que los editara, Vee-Jay, Capitol o United Artists.'
    },
    {
        id: '2331282',
        titulo: 'The Rise And Fall Of Ziggy Stardust And The Spiders From Mars',
        artista: 'David Bowie',
        categoria: 'Vinilo',
        anio: '1975',
        img: '/assets/R-2331282-1320026501.jpg',
        stock: 100,
        precio: 20.02,
        sello: 'RCA Victor',
        genero: 'Rock',
        descripcion: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars o también conocido simplemente como Ziggy Stardust, es el tí­tulo del quinto album de estudio y el primer album conceptual de David Bowie, publicado en 1972.'
    },
    {
        id: '354906',
        titulo: 'Aladdin Sane',
        artista: 'David Bowie',
        categoria: 'Vinilo',
        anio: '1973',
        img: '/assets/R-354906-1412775755-4012.jpg',
        stock: 100,
        precio: 25.34,
        sello: 'RCA Victor',
        genero: 'Rock',
        descripcion: 'Aladdin Sane es el tí­tulo del sexto Disco de estudio del artista británico David Bowie, publicado por la discogrpafica RCA Records en el año 1973.'
    },
    {
        id: '1349108',
        titulo: 'Axis: Bold As Love',
        artista: 'The Jimi Hendrix Experience',
        categoria: 'Vinilo',
        anio: '1968',
        img: '/assets/R-1349108-1579472688-6844.jpg',
        stock: 100,
        precio: 23.22,
        sello: 'Reprise Records',
        genero: 'Rock',
        descripcion: 'Axis: Bold as Love es el segundo álbum de The Jimi Hendrix Experience, lanzado en 1967 por Track Records. Este álbum suele ser considerado inferior a su antecesor Are You Experienced?, y los sencillos que fueron grabados en su momento no fueron tan exitosos como los anteriores.'
    },
    {
        id: '3526708',
        titulo: 'Lets Get Goin',
        artista: 'Marcel Riesco',
        categoria: 'Simple',
        anio: '2011',
        img: '/assets/R-11914604-1524657258-4011.jpg',
        stock: 5,
        precio: 23.22,
        sello: 'Sleazy Records',
        genero: 'Rockabilly',
        descripcion: 'Marcel Riesco desde comienzos del siglo XXI ha desarrollado una de las carreras más interesantes de la escena del rockabilly actual.Liderando Truly Love Trio al principio pero luego desarrollando su propio proyecto, en el que tiene cabida el rock´n´roll, pero también el country, el pop, las baladas… y es que la voz de Marcel es tan especial que puede permitirse arriesgar en casi cualquier registro y salir victorioso.'
    },
    {
        id: '11914604',
        titulo: 'The Queen Of Rockabilly Salutes The King Of Rock N Roll',
        artista: 'Wanda Jackson',
        categoria: 'Vinilo',
        anio: '2011',
        img: '/assets/R-3526708-1333924363.jpg',
        stock: 5,
        precio: 23.22,
        sello: 'Rock-A-Billy Records',
        genero: 'Rockabilly',
        descripcion: 'A very special tribute album to Elvis Presley recorded by Elvis’ close friend and protégé, Wanda Jackson!'
    },
    
]

export const getDiscos = () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(discos)
        }, 1000)
    })
}

export const getDiscoById = (discId) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(discos.find(disc => disc.id === discId))
        }, 1000)
    })
}
